site_name: MetSim 
site_description: Meteorology Simulator
site_author: Andrew Bennett 
repo_url: https://github.com/arbennett/MetSim
theme: readthedocs

pages:
# Main pages
- ['index.md', 'Home']

copyright: 'Copyright &copy; 2015, <a href="www.hydro.washington.edu/">University of Washington Computational Hydrology Group</a>.'
